name: CI/CD
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Descargando el codigo
              uses: actions/checkout@v3
            
            - name: Logeandome en Docker
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Construyendo y Subiendo imagen
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: michelcs/repochilito:mi-servidor-web

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Descargando archivos
              uses: actions/checkout@v3

            - name: Entrando a la ec2
              run: |
                echo "Creando la llave en el server"
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.ip_server }} >> ~/.ssh/known_hosts
                ssh -i ~/.ssh/id_rsa ${{ secrets.user }}@${{ secrets.ip_server }} << 'EOF'
                  ls 
                EOF
