name: CI/CD
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Descargando el codigo
              uses: actions/checkout@v3
            
            - name: Logeandome en Docker
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Construyendo y Subiendo imagen
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: michelcs/repochilito:mi-servidor-web

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Descargando archivos
              uses: actions/checkout@v3

            - name: Entrando a la ec2
              run: |
                echo "Creando la llave en el server"
                mkdir -p ~/.ssh
                cat ${{ secrets.SSH_KEY }} > ~/.ssh/ssh_rsa
                chmod 600 ~/.ssh/ssh_rsa
                ssh -i ~/.ssh/ssh_rsa ec2-user@18.188.169.21 << EOF
                  ls 
                EOF
